/**
 * TestRail TMS connector — read, push, and update test cases via TestRail REST API v2.
 *
 * Required env vars:
 *   TESTRAIL_URL          e.g. https://yourcompany.testrail.io
 *   TESTRAIL_USER         your.email@company.com
 *   TESTRAIL_API_KEY      your TestRail API key
 *   TESTRAIL_PROJECT_ID   integer project ID (find in TestRail URL)
 */

import {
  TestCase, TestResult, TCStep, TCType, TCPriority, ExecutionStatus,
  TMSReadResult, TMSPushResult, TMSUpdateResult,
} from './types';

function getConfig() {
  const url = process.env.TESTRAIL_URL?.replace(/\/$/, '');
  const user = process.env.TESTRAIL_USER;
  const key = process.env.TESTRAIL_API_KEY;
  const projectId = process.env.TESTRAIL_PROJECT_ID;

  if (!url || !user || !key || !projectId) {
    throw new Error(
      'TestRail requires: TESTRAIL_URL, TESTRAIL_USER, TESTRAIL_API_KEY, TESTRAIL_PROJECT_ID'
    );
  }

  const auth = Buffer.from(`${user}:${key}`).toString('base64');
  return { url, auth, projectId };
}

async function trFetch<T>(path: string, opts?: RequestInit): Promise<T> {
  const { url, auth } = getConfig();
  const res = await fetch(`${url}/index.php?/api/v2${path}`, {
    ...opts,
    headers: {
      Authorization: `Basic ${auth}`,
      'Content-Type': 'application/json',
      ...(opts?.headers || {}),
    },
  });
  if (!res.ok) {
    const err = await res.text();
    throw new Error(`TestRail API error ${res.status} on ${path}: ${err}`);
  }
  return res.json() as Promise<T>;
}

// ─── READ ─────────────────────────────────────────────────────────────────────

export async function readTestRailTCs(opts: {
  issueId?: string;
  suite?: string;
  caseIds?: string[];
}): Promise<TMSReadResult> {
  const { projectId } = getConfig();

  // Get all suites in the project
  const suites = await trFetch<{ id: number; name: string }[]>(`/get_suites/${projectId}`);

  let suiteId: number | undefined;
  let suiteName: string | undefined;

  if (opts.suite) {
    const match = suites.find((s) => s.name.toLowerCase() === opts.suite!.toLowerCase());
    if (!match) throw new Error(`TestRail suite "${opts.suite}" not found`);
    suiteId = match.id;
    suiteName = match.name;
  } else if (opts.issueId) {
    // Look for a suite named after the issue ID
    const match = suites.find((s) => s.name.includes(opts.issueId!));
    suiteId = match?.id;
    suiteName = match?.name;
  }

  let cases: TestRailCase[];

  if (opts.caseIds?.length) {
    // Fetch specific cases by their TestRail ID (strip 'C' prefix if present)
    const numericIds = opts.caseIds.map((id) => parseInt(id.replace(/^C/i, '')));
    cases = await Promise.all(numericIds.map((id) => trFetch<TestRailCase>(`/get_case/${id}`)));
  } else if (suiteId) {
    const result = await trFetch<{ cases: TestRailCase[] }>(`/get_cases/${projectId}&suite_id=${suiteId}`);
    cases = result.cases;
  } else {
    throw new Error('Provide --suite, --issue, or --case to read from TestRail');
  }

  return {
    tms: 'testRail',
    testCases: cases.map(normalizeTestRailCase),
    suiteId: suiteId ? String(suiteId) : undefined,
    suiteName,
  };
}

// ─── PUSH ─────────────────────────────────────────────────────────────────────

export async function pushToTestRail(opts: {
  issueId: string;
  suiteName: string;
  testCases: TestCase[];
}): Promise<TMSPushResult> {
  const { projectId } = getConfig();

  // Create a suite named after the issue
  const suite = await trFetch<{ id: number }>(`/add_suite/${projectId}`, {
    method: 'POST',
    body: JSON.stringify({ name: opts.suiteName, description: `Generated by swayambhu-qa for ${opts.issueId}` }),
  });

  // Create a section for each TC type
  const sections = new Map<string, number>();
  for (const tc of opts.testCases) {
    if (!sections.has(tc.type)) {
      const section = await trFetch<{ id: number }>(`/add_section/${projectId}`, {
        method: 'POST',
        body: JSON.stringify({ suite_id: suite.id, name: tc.type }),
      });
      sections.set(tc.type, section.id);
    }
  }

  const pushedIds: string[] = [];

  for (const tc of opts.testCases) {
    const sectionId = sections.get(tc.type)!;
    const steps = tc.steps.map((s) => ({
      content: s.action + (s.testData ? ` [Data: ${s.testData}]` : ''),
      expected: s.expectedResult,
    }));

    const created = await trFetch<{ id: number }>(`/add_case/${sectionId}`, {
      method: 'POST',
      body: JSON.stringify({
        title: `${tc.id}: ${tc.title}`,
        type_id: 1,    // Automated
        priority_id: priorityToTestRail(tc.priority),
        custom_steps_separated: steps,
        refs: opts.issueId,
      }),
    });

    pushedIds.push(`C${created.id}`);
    console.error(`  Created: C${created.id} — ${tc.title}`);
  }

  return { tms: 'testRail', issueId: opts.issueId, suiteName: opts.suiteName, pushedIds };
}

// ─── UPDATE ───────────────────────────────────────────────────────────────────

export async function updateTestRailResults(opts: {
  runId: string;
  results: TestResult[];
}): Promise<TMSUpdateResult> {
  const bulkResults = opts.results.map((r) => ({
    case_id: parseInt((r.nativeId || r.tcId).replace(/^C/i, '')),
    status_id: executionStatusToTestRail(r.status),
    comment: r.errorMessage || `${r.status} via ${r.tool} — swayambhu-qa`,
    elapsed: r.durationMs ? `${Math.ceil(r.durationMs / 1000)}s` : undefined,
  }));

  try {
    await trFetch(`/add_results_for_cases/${opts.runId}`, {
      method: 'POST',
      body: JSON.stringify({ results: bulkResults }),
    });
    return { tms: 'testRail', updated: opts.results.length, failed: 0 };
  } catch (err) {
    console.error('TestRail bulk update failed:', err);
    return { tms: 'testRail', updated: 0, failed: opts.results.length };
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

interface TestRailCase {
  id: number;
  title: string;
  type_id: number;
  priority_id: number;
  custom_steps_separated?: { content: string; expected: string }[];
  custom_preconds?: string;
  refs?: string;
}

function normalizeTestRailCase(tc: TestRailCase): TestCase {
  const steps: TCStep[] = (tc.custom_steps_separated || []).map((s, i) => ({
    stepNumber: i + 1,
    action: s.content,
    testData: '',
    expectedResult: s.expected,
  }));

  return {
    id: `C${tc.id}`,
    title: tc.title,
    type: testRailTypeToTC(tc.type_id),
    priority: testRailPriorityToTC(tc.priority_id),
    preconditions: tc.custom_preconds ? [tc.custom_preconds] : [],
    steps,
    automated: tc.type_id === 1,
    status: 'Ready',
    nativeId: String(tc.id),
  };
}

function testRailTypeToTC(typeId: number): TCType {
  const map: Record<number, TCType> = {
    1: 'Functional', 2: 'Functional', 3: 'Negative',
    4: 'API', 5: 'Accessibility', 6: 'Functional',
  };
  return map[typeId] || 'Functional';
}

function testRailPriorityToTC(priorityId: number): TCPriority {
  const map: Record<number, TCPriority> = { 1: 'P3', 2: 'P2', 3: 'P1', 4: 'P0' };
  return map[priorityId] || 'P2';
}

function priorityToTestRail(priority: TCPriority): number {
  return { P0: 4, P1: 3, P2: 2, P3: 1 }[priority];
}

function executionStatusToTestRail(status: ExecutionStatus): number {
  return { passed: 1, failed: 5, flaky: 4, skipped: 6, blocked: 2 }[status] || 6;
}
